<?php

/** @var string $module */

$strings = service('strings');
$ucf_module = $strings->get_Ucfirst($module);
$lc_module = $strings->get_Strtolower($module);

$code = "<?php\n";
$code .= "\n";
$code .= "namespace App\Modules\\$ucf_module\Controllers;\n";
$code .= "\n";
$code .= "use Higgs\API\ResponseTrait;\n";
$code .= "use Higgs\RESTful\ResourceController;\n";
$code .= "\n";
$code .= "/**\n";
$code .= "* Api\n";
$code .= "*/\n";
$code .= "class Api extends ResourceController\n";
$code .= "{\n";
$code .= "\t\tuse ResponseTrait;\n";
$code .= "\n";
$code .= "\t\tpublic \$namespace;\n";
$code .= "\t\tprotected \$prefix;\n";
$code .= "\t\tprotected \$module;\n";
$code .= "\t\tprotected \$views;\n";
$code .= "\t\tprotected \$viewer;\n";
$code .= "\t\tprotected \$component;\n";
$code .= "\n";
$code .= "\t\tpublic function __construct()\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t//header(\"Content-Type: text/json\");\n";
$code .= "\t\t\t\t  \$this->prefix = 'web-api';\n";
$code .= "\t\t\t\t  \$this->module = 'App\Modules\\$ucf_module';\n";
$code .= "\t\t\t\t  \$this->views = \$this->module . '\Views';\n";
$code .= "\t\t\t\t  \$this->viewer = \$this->views . '\index';\n";
$code .= "\t\t\t\t  \$this->component = \$this->views . '\Api';\n";
$code .= "\t\t\t    \thelper(\$this->module . '\Helpers\\$ucf_module');\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\t\t// all users\n";
$code .= "\t\tpublic function index()\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t\$data = array(\"message\" => \"Api Online!\");\n";
$code .= "\t\t\t\treturn \$this->respond(\$data);\n";
$code .= "\t\t}\n";
$code .= "\n";
$code .= "\n";
$code .= "\t\tpublic function test(string \$format, string \$option, string \$oid)\n";
$code .= "\t\t{\n";
$code .= "\t\t\t\t//header(\"Content-Type: text/json\");\n";
$code .= "\t\t\t\theader(\"Content-Type: text/html\");\n";
$code .= "\t\t\t\t\$data = array(\n";
$code .= "\t\t\t\t\t\t\"oid\" => \$oid\n";
$code .= "\t\t\t\t);\n";
$code .= "\t\t\t\tif (\$format == \"json\") {\n";
$code .= "\t\t\t\t\t\tif (\$option == 'list') {\n";
$code .= "\t\t\t\t\t\t\t\techo(view('App\Modules\\$ucf_module\Views\\test\List\json', \$data));\n";
$code .= "\t\t\t\t\t\t}\n";
$code .= "\t\t\t\t} else {\n";
$code .= "\t\t\t\t\t\treturn (\$this->failNotFound(lang(\"$ucf_module.Api-breaches-no-option\")));\n";
$code .= "\t\t\t\t}\n";
$code .= "\t\t}\n";
$code .= "}\n";
echo($code);
