<?php

include __DIR__ . '/_shared.php';

$code = "<?php\n";
$code .= "/** @var \$permissions array que contiene los permisos que el usuario no posee */\n";
$code .= "/** @var \$authentication \\App\\Libraries\\Authentication */\n";
$code .= "\n";
$code .= get_development_code_copyright(['path' => $g->namespaced . 'deny.php']);
$code .= "use Higgs\\Frontend\\Bootstrap\\v5_3_3\\Bootstrap as BS5;\n";
$code .= "\n";
$code .= "\$continue = \"/{$g->slc_module}/{$g->slc_component}/list/\".lpk();\n";
$code .= "if (\$authentication->get_LoggedIn()) {\n";
$code .= "    \$_icon = (string)BS5::icon(['icon' => 'ban', 'style' => 'duotone', 'size' => '4x']);\n";
$code .= "    \$_body = '<div class=\"text-center py-3\">' . \$_icon . '</div>'\n";
$code .= "        . '<p class=\"text-center pb-2\">' . lang('App.Access-denied-message') . '</p>';\n";
$code .= "    \$_permissions=\"<p class=\\\"text-center pb-2\\\">Permisos requeridos: \".implode(\" - \",\$permissions).\"</p>\";\n";
$code .= "    \$_continue = BS5::button(['content' => lang('App.Continue'), 'variant' => 'danger', 'size' => 'md', 'attributes' => ['href' => \$continue]]);\n";
$code .= "    \$card = BS5::card([\n";
$code .= "        'header' => [\n";
$code .= "            'title' => lang('App.Access-denied-title'),\n";
$code .= "            'class' => 'bg-danger border-danger text-white'\n";
$code .= "        ],\n";
$code .= "        'content' => [\n";
$code .= "            'htmlContent'=>\$_body.\$_permissions,\n";
$code .= "            'class' => 'bg-danger text-white',\n";
$code .= "        ],\n";
$code .= "        'footer' => [\n";
$code .= "            'content' => \$_continue,\n";
$code .= "            'class' => 'bg-danger text-white d-flex justify-content-end',\n";
$code .= "        ],\n";
$code .= "        'attributes' => [\n";
$code .= "            'class' => 'border-danger shadow-sm'\n";
$code .= "        ],\n";
$code .= "    ]);\n";
$code .= "} else {\n";
$code .= "    \$_icon = (string)BS5::icon(['icon' => 'lock', 'style' => 'duotone', 'size' => '4x']);\n";
$code .= "    \$_body = '<div class=\"text-center py-3\">' . \$_icon . '</div>'\n";
$code .= "        . '<p class=\"text-center pb-2\">' . lang('App.login-required-message') . '</p>';\n";
$code .= "    \$_continue = BS5::button(['content' => lang('App.Continue'), 'variant' => 'danger', 'size' => 'md', 'attributes' => ['href' => \$continue]]);\n";
$code .= "    \$card = BS5::card([\n";
$code .= "        'header' => [\n";
$code .= "            'title' => lang('App.login-required-title'),\n";
$code .= "            'class' => 'bg-danger text-white'\n";
$code .= "        ],\n";
$code .= "        'content' => [\n";
$code .= "            'htmlContent'=>\$_body,\n";
$code .= "            'class' => 'bg-danger text-white',\n";
$code .= "        ],\n";
$code .= "        'footer' => [\n";
$code .= "            'content' => \$_continue,\n";
$code .= "            'class' => 'bg-danger text-white d-flex justify-content-end',\n";
$code .= "        ],\n";
$code .= "        'attributes' => [\n";
$code .= "            'class' => 'border-danger shadow-sm'\n";
$code .= "        ],\n";
$code .= "    ]);\n";
$code .= "}\n";
$code .= "echo(\$card);\n";
$code .= '?>';

echo($code);
