<?php

include __DIR__ . '/_shared.php';

$code = "<?php\n";
$code .= get_development_code_copyright(['path' => $g->namespaced . 'processor.php']);
$code .= "use Higgs\\Frontend\\Bootstrap\\v5_3_3\\Bootstrap as BS5;\n";
$code .= "//[Inherited from ModuleController]---------------------------------------------------\n";
$code .= "// \$authentication  → service('authentication')  App\\Libraries\\Authentication\n";
$code .= "// \$bootstrap       → service('bootstrap')\n";
$code .= "// \$dates           → service('Dates')           App\\Libraries\\Dates\n";
$code .= "// \$strings         → service('strings')         App\\Libraries\\Strings\n";
$code .= "// \$request         → service('request')\n";
$code .= "// \$server          → service('server')\n";
$code .= "// \$parent          → ModuleController instance  (use \$parent->get_Array() for view data)\n";
$code .= "\$f = service(\"forms\", array(\"lang\" => \"{$g->ucf_module}_{$g->ucf_component}.\"));\n";
$code .= "//\$model = model(\"App\\Modules\\{$g->ucf_module}\\Models\\{$g->ucf_module}_{$g->ucf_component}\");\n";
$code .= "\$pkey= \$f->get_Value(\"pkey\");\n";
$code .= "\$row = \$model->withDeleted()->find(\$pkey);\n";
$code .= "/* Vars */\n";
$code .= "\$l[\"back\"]=\$f->get_Value(\"back\");\n";
$code .= "\$l[\"edit\"]=\"/{$g->slc_module}/{$g->slc_component}/edit/{\$pkey}\";\n";
$code .= "\$vsuccess=\"{$g->slc_module}/{$g->slc_component}-delete-success-message.mp3\";\n";
$code .= "\$vnoexist=\"{$g->slc_module}/{$g->slc_component}-delete-noexist-message.mp3\";\n";
$code .= "/* Build */\n";
$code .= "if (isset(\$row[\"{$g->fields[0]}\"])) {\n";
$code .= "    \$delete = \$model->delete(\$pkey);\n";
$code .= "    \$_icon = (string)BS5::icon(['icon' => 'circle-check', 'style' => 'duotone', 'size' => '4x']);\n";
$code .= "    \$_body = '<div class=\"text-center py-3\">' . \$_icon . '</div>'\n";
$code .= "        . '<p class=\"text-center pb-2\">' . lang(\"{$g->ucf_module}_{$g->ucf_component}.delete-success-message\") . '</p>'\n";
$code .= "        . '<div class=\"text-center pb-3\">' . (string)BS5::button(['content' => lang('App.Continue'), 'variant' => 'success', 'size' => 'md', 'attributes' => ['href' => \$l['back']]]) . '</div>';\n";
$code .= "    \$_content = (string)BS5::col(['attributes' => ['class' => 'text-center'], 'htmlContent' => \$_body]);\n";
$code .= "    \$c = BS5::card([\n";
$code .= "        'header' => [\n";
$code .= "            'title' => lang(\"{$g->ucf_module}_{$g->ucf_component}.delete-success-title\"),\n";
$code .= "            'class' => 'bg-success border-success text-white'\n";
$code .= "        ],\n";
$code .= "        'content' => [\n";
$code .= "            'htmlContent' => \$_content,\n";
$code .= "            'class' => 'bg-success text-white'\n";
$code .= "        ],\n";
$code .= "        'attributes'  => ['class' => 'border-success shadow-sm'],\n";
$code .= "    ]);\n";
$code .= "} else {\n";
$code .= "    \$_icon = (string)BS5::icon(['icon' => 'triangle-exclamation', 'style' => 'duotone', 'size' => '4x']);\n";
$code .= "    \$_body = '<div class=\"text-center py-3\">' . \$_icon . '</div>'\n";
$code .= "        . '<p class=\"text-center pb-2\">' . lang(\"{$g->ucf_module}_{$g->ucf_component}.delete-noexist-message\") . '</p>'\n";
$code .= "        . '<div class=\"text-center pb-3\">' . (string)BS5::button(['content' => lang('App.Continue'), 'variant' => 'warning', 'size' => 'md', 'attributes' => ['href' => \$l['back']]]) . '</div>';\n";
$code .= "    \$_content = (string)BS5::col(['attributes' => ['class' => 'text-center'], 'htmlContent' => \$_body]);\n";
$code .= "    \$c = BS5::card([\n";
$code .= "        'header' => [\n";
$code .= "            'title' => lang(\"{$g->ucf_module}_{$g->ucf_component}.delete-noexist-title\"),\n";
$code .= "            'class' => 'bg-warning border-warning text-dark'\n";
$code .= "        ],\n";
$code .= "        'content' => [\n";
$code .= "            'htmlContent' => \$_content,\n";
$code .= "            'class' => 'bg-warning text-dark'\n";
$code .= "        ],\n";
$code .= "        'attributes'  => ['class' => 'border-warning shadow-sm'],\n";
$code .= "    ]);\n";
$code .= "}\n";
$code .= "echo(\$c);\n";
$code .= "\$model->invalidateSearchCache();\n";
$code .= "?>\n";

echo($code);
